### ISSUE TITLE
On the trendline, show just the datapoint across all parameters instead of the blackline

### ISSUE THREAD

**Issue by wai2k** [HealthForge/hackday-nhs-14may2016#16]
![bloodflow](https://cloud.githubusercontent.com/assets/1630790/15377090/14d9c51e-1d51-11e6-8ef5-c4d11338d4fd.png)

I find the blackline interferes with my perception of the trendlines. Also the data points can contain the actual value too.

**Comment by jam13** [comment]
I have dropped the index line right back so it's less distracting, and the hover points are now linked for all graphs.

Hover values have moved from the graph to the left hand panel to avoid cluttering the line.
