### ISSUE TITLE
Showing the numerical values on every graph and not just the active test

### ISSUE THREAD

**Issue by wai2k** [HealthForge/hackday-nhs-14may2016#9]
![bloodflow](https://cloud.githubusercontent.com/assets/1630790/15343255/2bd0baf2-1c93-11e6-9869-d01979c1b18f.png)

**Comment by jam13** [comment]
The value on hover feature needs quite a bit of work, and it was my intention to do exactly what you are suggesting.

**Comment by jam13** [comment]
This is now done, but the values are shown in the left hand panel rather than overlaid on the graph.
